/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Informes.java
 *
 * Created on May 16, 2012, 11:24:24 PM
 */
package soprafamrv;

import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import soprafamrv.ARCHIVOS_EXP.GeneratePDF;
import soprafamrv.BD.Conexion;
import soprafamrv.SISTEMA.vehiculo;

/**
 *
 * @author Cri
 */
public class Informe extends javax.swing.JInternalFrame {

    /** Creates new form Informes */
    public Informe() {
        initComponents();
        asignarBotones();
    }
    
    private void asignarBotones(){
        //Tab Vehiculo
        GrupoBotonesBusqueda.add(JRADBUTANOVEHI);
        GrupoBotonesBusqueda.add(JRADBUTANOINGR);
        GrupoBotonesBusqueda.add(JRADBUTANORETI);
        GrupoBotonesBusqueda.add(JRADBUTMARCAVE);        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesBusqueda = new javax.swing.ButtonGroup();
        GrupoBotonePanelTiempo = new javax.swing.ButtonGroup();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        JFANO = new javax.swing.JFormattedTextField();
        JLREPMESINICIAL = new javax.swing.JLabel();
        JLREPMESFINAL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        JBCargarDatosVehiculo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JRADBUTANOVEHI = new javax.swing.JRadioButton();
        JRADBUTANOINGR = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        JRADBUTANORETI = new javax.swing.JRadioButton();
        JRADBUTMARCAVE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(soprafamrv.SOPRAFAMRVApp0.class).getContext().getResourceMap(Informe.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel16.border.title"))); // NOI18N
        jPanel16.setName("jPanel16"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        try {
            JFANO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFANO.setText(resourceMap.getString("JFANO.text")); // NOI18N
        JFANO.setToolTipText(resourceMap.getString("JFANO.toolTipText")); // NOI18N
        JFANO.setEnabled(false);
        JFANO.setName("JFANO"); // NOI18N

        JLREPMESINICIAL.setName("JLREPMESINICIAL"); // NOI18N

        JLREPMESFINAL.setName("JLREPMESFINAL"); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(JLREPMESINICIAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(JLREPMESFINAL)
                .addGap(18, 18, 18))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel14)
                .addGap(9, 9, 9)
                .addComponent(JFANO, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFANO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLREPMESINICIAL)
                    .addComponent(JLREPMESFINAL)))
        );

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel6.border.title"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        JBCargarDatosVehiculo.setText(resourceMap.getString("JBCargarDatosVehiculo.text")); // NOI18N
        JBCargarDatosVehiculo.setEnabled(false);
        JBCargarDatosVehiculo.setName("JBCargarDatosVehiculo"); // NOI18N
        JBCargarDatosVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCargarDatosVehiculoActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel7.border.title"))); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        JRADBUTANOVEHI.setText(resourceMap.getString("JRADBUTANOVEHI.text")); // NOI18N
        JRADBUTANOVEHI.setName("JRADBUTANOVEHI"); // NOI18N
        JRADBUTANOVEHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRADBUTANOVEHIActionPerformed(evt);
            }
        });

        JRADBUTANOINGR.setText(resourceMap.getString("JRADBUTANOINGR.text")); // NOI18N
        JRADBUTANOINGR.setName("JRADBUTANOINGR"); // NOI18N
        JRADBUTANOINGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRADBUTANOINGRActionPerformed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        JRADBUTANORETI.setText(resourceMap.getString("JRADBUTANORETI.text")); // NOI18N
        JRADBUTANORETI.setName("JRADBUTANORETI"); // NOI18N
        JRADBUTANORETI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRADBUTANORETIActionPerformed(evt);
            }
        });

        JRADBUTMARCAVE.setText(resourceMap.getString("JRADBUTMARCAVE.text")); // NOI18N
        JRADBUTMARCAVE.setName("JRADBUTMARCAVE"); // NOI18N
        JRADBUTMARCAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRADBUTMARCAVEActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRADBUTANOINGR)
                    .addComponent(JRADBUTANOVEHI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(JRADBUTMARCAVE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JRADBUTANORETI)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRADBUTANOVEHI)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRADBUTANOINGR)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRADBUTMARCAVE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JRADBUTANORETI))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(JBCargarDatosVehiculo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCargarDatosVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void JBCargarDatosVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCargarDatosVehiculoActionPerformed
    int ANO_INICIAL = Integer.parseInt(this.JFANO.getText());
    if (this.JRADBUTANOVEHI.isSelected()){
            try {             
                String anoVeh = "select patente, chasis, marca, modelo, ano from vehiculo where ano = "+ANO_INICIAL+"";
                ResultSet rsDatos = Conexion.ejecutarQuery(anoVeh);
                                
                ResultSet rsGrafico = Conexion.ejecutarQuery(anoVeh);
                //Generacion Documento
                GeneratePDF gpdf = new GeneratePDF();    
                gpdf.crearDocumento("INFORME VEHICULOS AÑO - "+ANO_INICIAL);
                gpdf.ContenidoInformeVehiculos("SOPRAF S.A. - SOFTWARE AMRV", "I  N  F  O  R  M  E    P  O  R    A  Ñ  O    V  E  H  I  C  U  L  O", "V  E  H  I  C  U  L  O  S", rsDatos, rsGrafico);
                   
        } catch (FileNotFoundException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Debe cerrar el documento actual para poder crearlo nuevamente", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (DocumentException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error2", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error3", "Mensajero", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex){
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error4", "Mensajero", JOptionPane.ERROR_MESSAGE);
        }

    }
    else if(this.JRADBUTANOINGR.isSelected()){
        try {   
            //agregar a todas las query el año
                String RepUsados = "Select r.nombre as NOMBRE, sum(otr.cantidad) as TOTAL_USADO from orden_trabajo_repuesto otr, repuesto r, orden_trabajo ot where otr.id_repuesto = r.id_repuesto and ot.fecha_inicio between to_date('01-' || 1 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and last_day(to_date('31-' || 12 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')) and rownum <11 group by r.id_repuesto, r.nombre order by TOTAL_USADO desc"; 
                String RepCompraXaño = "Select sum(cd.cantidad) as TOTAL_AÑO, r.nombre as Nombre, c.fecha_compra as Fecha_compra from compra_detalle cd, repuesto r, compra c where cd.nro_factura = c.nro_factura and cd.id_repuesto = r.id_repuesto and c.fecha_compra between to_date('01-' || 1 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and last_day(to_date('31-' || 12 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')) group by r.nombre, c.fecha_compra";
                String StockRep = "select r.nombre as nombre, sum(r.cantidad) as TOTAL from repuesto r group by r.nombre order by TOTAL desc";
                String RepUsadoXvehi = "select otr.id_ot AS NUMERO_ORDEN, otr.patente AS PATENTE, r.nombre AS REPUESTO, sum(otr.cantidad) as TOTAL from repuesto r, orden_trabajo ot, orden_trabajo_repuesto otr WHERE ot.id_ot = otr.id_ot and ot.patente = otr.patente and otr.id_repuesto = r.id_repuesto and ot.fecha_inicio between to_date('01-' || 1 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and last_day(to_date('31-' || 12 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')) group by otr.id_ot, otr.patente, r.nombre order by TOTAL desc";
                String RepXmecan = "select m.rut_mecanico as RUT_MECANICO, m.nombre AS NOMBRE, m.apellido_paterno AS APELLIDO_PATERNO, m.apellido_materno AS APELLIDO_MATERNO, ot.id_ot AS ID_ORDEN, ot.patente AS PATENTE, r.nombre AS NOMBRE_REPUESTO, sum(otr.cantidad) as TOTAL from repuesto r, orden_trabajo ot, orden_trabajo_repuesto otr, mecanico m where ot.id_ot = otr.id_ot and ot.patente = otr.patente and otr.id_repuesto = r.id_repuesto and ot.rut_mecanico = m.rut_mecanico and ot.fecha_inicio between to_date('01-' || 1 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and last_day(to_date('31-' || 12 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')) group by m.rut_mecanico, m.nombre, m.apellido_paterno, m.apellido_materno, ot.id_ot, ot.patente, r.nombre order by TOTAL desc"; 
                String RepXencb = "select eb.rut_encargado as RUT_ENCARGADO, eb.nombre AS NOMBRE, eb.apellido_paterno AS APELLIDO_PATERNO, eb.apellido_materno AS APELLIDO_MATERNO, ot.id_ot AS ID_ORDEN, ot.patente AS PATENTE, r.nombre AS NOMBRE_REPUESTO, sum(otr.cantidad) as TOTAL from repuesto r, orden_trabajo ot, orden_trabajo_repuesto otr, encargado_bodega eb WHERE ot.id_ot = otr.id_ot and ot.patente = otr.patente and otr.id_repuesto = r.id_repuesto and otr.rut_encargado = eb.rut_encargado and ot.fecha_inicio between to_date('01-' || 1 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and last_day(to_date('31-' || 12 || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')) group by eb.rut_encargado, eb.nombre, eb.apellido_paterno, eb.apellido_materno, ot.id_ot, ot.patente, r.nombre order by TOTAL desc";
                
                               
                ResultSet rsRepUsados = Conexion.ejecutarQuery(RepUsados);                
                ResultSet rsRepCompraXaño = Conexion.ejecutarQuery(RepCompraXaño);
                ResultSet rsStockRep = Conexion.ejecutarQuery(StockRep);
                ResultSet rsRepUsadoXvehi = Conexion.ejecutarQuery(RepUsadoXvehi);
                ResultSet rsRepXmecan = Conexion.ejecutarQuery(RepXmecan);
                ResultSet rsRepXencb = Conexion.ejecutarQuery(RepXencb);
                
                //Generacion Documento
                GeneratePDF gpdf = new GeneratePDF();    
                gpdf.crearDocumento("INFORME REPUESTOS AÑO - "+ANO_INICIAL);
                gpdf.ContenidoInformeRepuestos("SOPRAF S.A. - SOFTWARE AMRV", "I  N  F  O  R  M  E    A  N  U  A  L    R  E  P  U  E  S  T  O  S   -   " +ANO_INICIAL, "R  E  P  U  E  S  T  O  S", rsRepUsados, rsRepCompraXaño, rsStockRep, rsRepUsadoXvehi, rsRepXmecan, rsRepXencb);
        
            
               } catch (FileNotFoundException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Debe cerrar el documento actual para poder crearlo nuevamente", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (DocumentException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error2", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error3", "Mensajero", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex){
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error4", "Mensajero", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    else if (this.JRADBUTANORETI.isSelected()){
            try {
                String FallaXaño = "select count(otf.id_falla) as TOTAL_FALLAS from orden_trabajo_falla otf, orden_trabajo ot, vehiculo v, falla f where ot.id_ot = otf.id_ot and ot.patente = otf.patente and ot.patente = v.patente and f.id_falla = otf.id_falla and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')))"; 
                String MasDetect = "select f.nombre as NOMBRE, otf.id_falla as ID_FALLA, count(f.id_falla) as TOTAL from orden_trabajo_falla otf, orden_trabajo ot, vehiculo v, falla f where otf.id_ot = ot.id_ot and ot.patente = otf.patente and ot.patente = v.patente and f.id_falla = otf.id_falla and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) and rownum <11 group by f.nombre, otf.id_falla order by TOTAL desc ";
                String FallaXvehi = "Select otf.patente as PATENTE, f.nombre as NOMBRE, count(otf.id_falla) as TOTAL from falla f, orden_trabajo ot, orden_trabajo_falla otf, vehiculo v where ot.id_ot = otf.id_ot and ot.patente = otf.patente and otf.id_falla = f.id_falla and ot.patente = v.patente and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) group by otf.patente, f.nombre ";
                String FallaXmeca = "Select m.rut_mecanico as RUT_MECANICO, m.nombre AS NOMBRE, m.apellido_paterno AS APELLIDO_PATERNO, m.apellido_materno AS APELLIDO_MATERNO,otf.id_ot as ID_ORDEN, otf.patente AS PATENTE, f.nombre as NOMBRE_FALLA, count(otf.id_falla) as TOTAL from falla f, orden_trabajo ot, orden_trabajo_falla otf, mecanico m where ot.id_ot = otf.id_ot and ot.patente = otf.patente and otf.id_falla = f.id_falla and ot.rut_mecanico = m.rut_mecanico and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) group by m.rut_mecanico, m.nombre, m.apellido_paterno, m.apellido_materno, otf.id_ot, otf.patente, f.nombre ";        
                
                ResultSet rsFallaXaño = Conexion.ejecutarQuery(FallaXaño);
                ResultSet rsMasDetect = Conexion.ejecutarQuery(MasDetect);
                ResultSet rsFallaXvehi = Conexion.ejecutarQuery(FallaXvehi);
                ResultSet rsFallaXmeca = Conexion.ejecutarQuery(FallaXmeca);
                
                //Generacion Documento
                GeneratePDF gpdf = new GeneratePDF();    
                gpdf.crearDocumento("INFORME FALLAS AÑO - "+ANO_INICIAL);
                gpdf.ContenidoInformeFallas("SOPRAF S.A. - SOFTWARE AMRV", "I  N  F  O  R  M  E    A  N  U  A  L    F  A  L  L  A  S   -   " +ANO_INICIAL, "F  A  L  L  A  S", rsFallaXaño, rsMasDetect, rsFallaXvehi, rsFallaXmeca);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Debe cerrar el documento actual para poder crearlo nuevamente", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (DocumentException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error2", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error3", "Mensajero", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex){
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error4", "Mensajero", JOptionPane.ERROR_MESSAGE);
        }
    }
    else if(this.JRADBUTMARCAVE.isSelected()){
            try {
                String otXaño = "select count(ot.id_ot) as TOTAL_OT from orden_trabajo ot where ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy')))";
                String otXveh = "Select ot.patente as PATENTE, count(ot.id_ot) as TOTAL_OT from orden_trabajo ot,  vehiculo v where ot.patente = v.patente and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) group by ot.patente ";
                String otXadm = "Select ad.rut_administrador AS RUT_ADMIN, ad.nombre AS NOMBRE, ad.apellido_paterno AS APELLIDO_PATERNO, ad.apellido_materno AS APELLIDO_MATERNO, ot.patente AS PATENTE, count(ot.id_ot) as TOTAL_POR_VEHICULO from orden_trabajo ot, administrador ad where ot.rut_administrador = ad.rut_administrador and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) group by ad.rut_administrador ,ad.nombre, ad.apellido_paterno, ad.apellido_materno, ot.patente ";
                String otXmec = "Select m.rut_mecanico AS RUT_MECANICO, m.nombre AS NOMBRE, m.apellido_paterno AS APELLIDO_PATERNO, m.apellido_materno AS APELLIDO_MATERNO, ot.patente AS PATENTE, count(ot.id_ot) as TOTAL_POR_VEHICULO from orden_trabajo ot, mecanico m where ot.rut_mecanico = m.rut_mecanico and ot.fecha_inicio between to_date('01-' || '1' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy') and to_date(last_day(to_date('31-' || '12' || '-' || "+ANO_INICIAL+",'dd-mm-yyyy'))) group by m.rut_mecanico, m.nombre, m.apellido_paterno, m.apellido_materno, ot.patente ";
                
                ResultSet rsotXaño = Conexion.ejecutarQuery(otXaño);
                ResultSet rsotXveh = Conexion.ejecutarQuery(otXveh);
                ResultSet rsotXadm = Conexion.ejecutarQuery(otXadm);
                ResultSet rsotXmec = Conexion.ejecutarQuery(otXmec);
                
                //Generacion Documento
                GeneratePDF gpdf = new GeneratePDF();    
                gpdf.crearDocumento("INFORME ORDENES DE TRABAJO AÑO - "+ANO_INICIAL);
                gpdf.ContenidoInformeOT("SOPRAF S.A. - SOFTWARE AMRV", "I  N  F  O  R  M  E    A  N  U  A  L    O  T   -   " +ANO_INICIAL, "O  R  D  E  N  E  S    D  E    T  R  A  B  A  J  O", rsotXaño, rsotXveh, rsotXadm, rsotXmec);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Debe cerrar el documento actual para poder crearlo nuevamente", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (DocumentException ex) {
            Logger.getLogger(vehiculo.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error2", "Mensajero", JOptionPane.ERROR_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error3", "Mensajero", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex){
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error4", "Mensajero", JOptionPane.ERROR_MESSAGE);
        }
        
    }    
}//GEN-LAST:event_JBCargarDatosVehiculoActionPerformed

private void JRADBUTANOVEHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRADBUTANOVEHIActionPerformed
    this.JFANO.setEnabled(true);    
    this.JBCargarDatosVehiculo.setEnabled(true);
    
}//GEN-LAST:event_JRADBUTANOVEHIActionPerformed

private void JRADBUTANOINGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRADBUTANOINGRActionPerformed
    this.JFANO.setEnabled(true);    
    this.JBCargarDatosVehiculo.setEnabled(true);
}//GEN-LAST:event_JRADBUTANOINGRActionPerformed

private void JRADBUTANORETIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRADBUTANORETIActionPerformed
    this.JFANO.setEnabled(true);    
    this.JBCargarDatosVehiculo.setEnabled(true);
}//GEN-LAST:event_JRADBUTANORETIActionPerformed

private void JRADBUTMARCAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRADBUTMARCAVEActionPerformed
    this.JFANO.setEnabled(true);    
    this.JBCargarDatosVehiculo.setEnabled(true);
}//GEN-LAST:event_JRADBUTMARCAVEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotonePanelTiempo;
    private javax.swing.ButtonGroup GrupoBotonesBusqueda;
    private javax.swing.JButton JBCargarDatosVehiculo;
    private javax.swing.JFormattedTextField JFANO;
    private javax.swing.JLabel JLREPMESFINAL;
    private javax.swing.JLabel JLREPMESINICIAL;
    private javax.swing.JRadioButton JRADBUTANOINGR;
    private javax.swing.JRadioButton JRADBUTANORETI;
    private javax.swing.JRadioButton JRADBUTANOVEHI;
    private javax.swing.JRadioButton JRADBUTMARCAVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
